AWSTemplateFormatVersion: 2010-09-09
Description: 'A Read only role for OpKoKo 2019.2'

Parameters:
  PermissionBoundryArn:
    Type: String

Resources:
  ReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', ['ConsoleReadUser', !Ref 'AWS::Region']]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'ds.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
      PermissionsBoundary: !Ref PermissionBoundryArn
